/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import dominio.Cliente;
import dominio.Cuenta;
import dominio.Retiro;
import excepciones.PersistenciaException;
import interfaces.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import utils.Utilerias;
import validador.Validadores;

/**
 *
 * @author koine
 */
public class DlgRetiro extends javax.swing.JDialog {

    private Validadores val = new Validadores();
    private static final Logger LOG = Logger.getLogger(DlgRegistro.class.getName());

    private final IClientesDAO clientesDAO;
    private final IRetirosDAO retirosDAO;
    private final ICuentasDAO cuentasDAO;

    /**
     * Constructor que inicializa los atributos al valor de sus parámetros
     *
     * @param parent
     * @param modal
     * @param clientesDAO
     * @param retirosDAO
     * @param cuentasDAO
     */
    public DlgRetiro(java.awt.Frame parent, boolean modal, IClientesDAO clientesDAO, IRetirosDAO retirosDAO, ICuentasDAO cuentasDAO) {
        super(parent, modal);
        this.clientesDAO = clientesDAO;
        this.retirosDAO = retirosDAO;
        this.cuentasDAO = cuentasDAO;
        initComponents();

    }

    /**
     * Método que valida el monto de la cuenta origen
     *
     * @return Cuenta con el monto válido
     */
    private Cuenta validarMontoCuentaOrigen() {
        int cuentaO = Integer.parseInt(txtCuenta.getText());
        float monto = Float.parseFloat(txtMonto.getText());

        if (monto > cuentasDAO.consultar(cuentaO).getSaldo()) {
            JOptionPane.showMessageDialog(this, "No fue posible realizar el retiro, dinero insuficiente en la cuenta", "ERROR", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        Cuenta cuenta = new Cuenta(cuentaO);
        return cuenta;
    }

    /**
     * Método que realiza el retiro
     *
     * @return Retiro realizado
     */
    public Retiro retiro() {

        try {
            Integer cuenta = validarMontoCuentaOrigen().getCodigo();
            float monto = Float.parseFloat(txtMonto.getText());
            String contrasenia = Utilerias.generarContrasenia(8);
            Retiro retiro = retirosDAO.retirar2(cuenta, monto, contrasenia);
            JOptionPane.showMessageDialog(this, "Se creó el folio de la cuenta: " + cuenta, "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
            return retiro;
        } catch (PersistenciaException ex) {
            LOG.log(Level.SEVERE, ex.getMessage());
            JOptionPane.showMessageDialog(this, "No fue posible realizar la transferencia", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblConsultar = new javax.swing.JLabel();
        lblCliente1 = new javax.swing.JLabel();
        lblCuenta = new javax.swing.JLabel();
        txtCuenta = new javax.swing.JTextField();
        txtFolio = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblSaldo1 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JTextField();
        lblMonto = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Retiro");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(149, 194, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblConsultar.setFont(new java.awt.Font("Microsoft YaHei", 1, 36)); // NOI18N
        lblConsultar.setForeground(new java.awt.Color(14, 47, 132));
        lblConsultar.setText("Retiro");
        jPanel2.add(lblConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        lblCliente1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        lblCliente1.setForeground(new java.awt.Color(14, 47, 132));
        lblCliente1.setText("Folio:");
        jPanel2.add(lblCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        lblCuenta.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        lblCuenta.setForeground(new java.awt.Color(14, 47, 132));
        lblCuenta.setText("Cuenta:");
        jPanel2.add(lblCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        txtCuenta.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jPanel2.add(txtCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 80, 40));

        txtFolio.setEditable(false);
        txtFolio.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jPanel2.add(txtFolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 170, 40));

        btnAceptar.setBackground(new java.awt.Color(72, 77, 197));
        btnAceptar.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 150, 60));

        btnCancelar.setBackground(new java.awt.Color(72, 77, 197));
        btnCancelar.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 160, 60));

        lblSaldo1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        lblSaldo1.setForeground(new java.awt.Color(14, 47, 132));
        lblSaldo1.setText("Contraseña:");
        jPanel2.add(lblSaldo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        txtContrasena.setEditable(false);
        txtContrasena.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jPanel2.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 160, 40));

        lblMonto.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        lblMonto.setForeground(new java.awt.Color(14, 47, 132));
        lblMonto.setText("Monto:");
        jPanel2.add(lblMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        txtMonto.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jPanel2.add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 80, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 440, 440));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        Retiro retiro = retiro();
        this.txtFolio.setText(retiro.getFolio().toString());
        this.txtContrasena.setText(retiro.getContrasena());
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCliente1;
    private javax.swing.JLabel lblConsultar;
    private javax.swing.JLabel lblCuenta;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblSaldo1;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtCuenta;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
