/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import dominio.Cliente;
import interfaces.IClientesDAO;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import validador.Validadores;

/**
 *
 * @author koine
 */
public class FrmInicio extends javax.swing.JFrame {
    private Cliente cliente = null;
    private Validadores val = new Validadores();
    private static final Logger LOG = Logger.getLogger(DlgRegistro.class.getName());
    
    private final IClientesDAO clientesDAO;
    /**
     * Creates new form FrmInicio
     * @param clientesDAO
     * @param cliente
     */
    public FrmInicio(IClientesDAO clientesDAO, Cliente cliente) {
        this.clientesDAO= clientesDAO;
        this.cliente = cliente;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuITransaccion = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuCuenta = new javax.swing.JMenu();
        menuICrearCuenta = new javax.swing.JMenuItem();
        menuICancelarCuenta = new javax.swing.JMenuItem();
        menuIActualizarDatos = new javax.swing.JMenuItem();
        menuIAcercaDe = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(149, 194, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(14, 47, 132));
        lblNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNombreMouseEntered(evt);
            }
        });
        jPanel3.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 270, 50));

        jButton1.setBackground(new java.awt.Color(72, 77, 197));
        jButton1.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Consulta cuenta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 193, 75));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\koine\\Documents\\GitHub\\Proyecto-1-Ebanca\\EBanca_CedanoM_SotoA\\src\\main\\java\\img\\Logo_Ebanca.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 510, 440));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 500));

        menuITransaccion.setText("Transaccion");
        menuITransaccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuITransaccionMouseClicked(evt);
            }
        });
        menuITransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuITransaccionActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuITransaccion);

        jMenu2.setText("Cuenta");

        menuCuenta.setText("Cuenta");

        menuICrearCuenta.setText("Crear cuenta");
        menuICrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuICrearCuentaActionPerformed(evt);
            }
        });
        menuCuenta.add(menuICrearCuenta);

        menuICancelarCuenta.setText("Cancelar cuenta");
        menuICancelarCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuICancelarCuentaMouseClicked(evt);
            }
        });
        menuICancelarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuICancelarCuentaActionPerformed(evt);
            }
        });
        menuCuenta.add(menuICancelarCuenta);

        jMenu2.add(menuCuenta);

        menuIActualizarDatos.setText("Actualizar datos");
        menuIActualizarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIActualizarDatosActionPerformed(evt);
            }
        });
        jMenu2.add(menuIActualizarDatos);

        jMenuBar1.add(jMenu2);

        menuIAcercaDe.setText("Acerca de");
        menuIAcercaDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuIAcercaDeMouseClicked(evt);
            }
        });
        menuIAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIAcercaDeActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuIAcercaDe);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuIAcercaDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuIAcercaDeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuIAcercaDeMouseClicked

    private void menuITransaccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuITransaccionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuITransaccionMouseClicked

    private void lblNombreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNombreMouseEntered
        this.lblNombre.setText(cliente.getNombres()+" "+cliente.getApPaterno()+" "+cliente.getApMaterno());
    }//GEN-LAST:event_lblNombreMouseEntered

    private void menuICancelarCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuICancelarCuentaMouseClicked
        new DlgCancelarCuenta(this, true, clientesDAO, cliente).setVisible(true);
    }//GEN-LAST:event_menuICancelarCuentaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new DlgConsultar(this, true, clientesDAO, cliente).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void menuICancelarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuICancelarCuentaActionPerformed
        new DlgCancelarCuenta(this, true, clientesDAO, cliente).setVisible(true);
    }//GEN-LAST:event_menuICancelarCuentaActionPerformed

    private void menuITransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuITransaccionActionPerformed
        new DlgTransferencia(this, true, clientesDAO, cliente).setVisible(true);
    }//GEN-LAST:event_menuITransaccionActionPerformed

    private void menuIAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIAcercaDeActionPerformed
        JOptionPane.showMessageDialog(this,"Michell Cedano, Alexa Soto","DESARROLLADORES", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_menuIAcercaDeActionPerformed

    private void menuICrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuICrearCuentaActionPerformed
        new DlgCrearCuenta(this, true, clientesDAO, cliente).setVisible(true);
    }//GEN-LAST:event_menuICrearCuentaActionPerformed

    private void menuIActualizarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIActualizarDatosActionPerformed
        new DlgActualizarDatos(this, true, clientesDAO, cliente).setVisible(true);
    }//GEN-LAST:event_menuIActualizarDatosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JMenu menuCuenta;
    private javax.swing.JMenu menuIAcercaDe;
    private javax.swing.JMenuItem menuIActualizarDatos;
    private javax.swing.JMenuItem menuICancelarCuenta;
    private javax.swing.JMenuItem menuICrearCuenta;
    private javax.swing.JMenu menuITransaccion;
    // End of variables declaration//GEN-END:variables
}
