/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import dominio.Cliente;
import interfaces.IClientesDAO;
import java.util.logging.Logger;
import validador.Validadores;

/**
 *
 * @author koine
 */
public class DlgRetiro extends javax.swing.JDialog {
    private Validadores val = new Validadores();
    private static final Logger LOG = Logger.getLogger(DlgRegistro.class.getName());
    
    private final IClientesDAO clientesDAO;
    
    /**
     * Creates new form DlgRetiro
     * @param parent
     */
    public DlgRetiro(java.awt.Frame parent, boolean modal, IClientesDAO clientesDAO) {
        super(parent, modal);
        this.clientesDAO= clientesDAO;
        initComponents();
    }

    public void retiro() {
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblConsultar = new javax.swing.JLabel();
        lblCliente1 = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JTextField();
        txtFolio = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Retiro");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(149, 194, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblConsultar.setFont(new java.awt.Font("Microsoft YaHei", 1, 36)); // NOI18N
        lblConsultar.setForeground(new java.awt.Color(14, 47, 132));
        lblConsultar.setText("Retiro");
        jPanel2.add(lblConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        lblCliente1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        lblCliente1.setForeground(new java.awt.Color(14, 47, 132));
        lblCliente1.setText("Folio:");
        jPanel2.add(lblCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        lblSaldo.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        lblSaldo.setForeground(new java.awt.Color(14, 47, 132));
        lblSaldo.setText("Contraseña:");
        jPanel2.add(lblSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));
        jPanel2.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 140, -1));
        jPanel2.add(txtFolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 140, -1));

        btnAceptar.setBackground(new java.awt.Color(72, 77, 197));
        btnAceptar.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 110, 50));

        btnCancelar.setBackground(new java.awt.Color(72, 77, 197));
        btnCancelar.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 120, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 430, 290));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        retiro();
        dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCliente1;
    private javax.swing.JLabel lblConsultar;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtFolio;
    // End of variables declaration//GEN-END:variables
}
